import { auth } from "@/auth";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Material Management System",
    description: "Generated by UIDev",
};

const MaterialManagement = async () => {
    const session = await auth();

    return (
        <div>Material Management</div>
    );
}

export default MaterialManagement;