import { auth } from "@/auth";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Payroll Management System",
    description: "Generated by UIDev",
};

const PayrollManagement = async () => {
    const session = await auth();

    return (
        <div>Payroll Management</div>
    );
}

export default PayrollManagement;