import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import Header from "@/components/app-menubar/header";
import SidebarPage from "@/components/app-menubar/sidenav";
import { Toaster } from "@/components/ui/sonner";
import SiteFooter from "@/components/app-menubar/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ERP System",
  description: "Generated by UIDev",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {session ? (
          <div className="flex w-full flex-col flex-nowrap" >
            <div className="fixed  top-0 left-0 right-0 z-50">
              <Header session={session} />
            </div>
            <div className="flex w-full flex-1">
              <SidebarPage session={session?.user} />
              <main className="flex-1 w-full mx-4 h-[calc(100%-125px)] my-16 overflow-hidden">
                {children}
                <Toaster position="bottom-center" richColors expand={false} />
              </main>
            </div>
            <div className="fixed  bottom-0 left-0 right-0 z-10">
              <SiteFooter />
            </div>
          </div>
        ) : (
          <div className="flex w-full flex-col flex-nowrap " >
            <div className="fixed  top-0 left-0 right-0 z-50">
              <Header session={session} />
            </div>
            <div className="flex w-full flex-1">
              {/* <SidebarPage session={session?.user} /> */}
              <main className="flex-1 w-full mx-4 my-10 overflow-hidden">
                {children}
                <Toaster position="bottom-center" richColors expand={false} />
              </main>
            </div>
            <div className="fixed  bottom-0 left-0 right-0 z-10">
              <SiteFooter />
            </div>
          </div>
        )}
      </body >
    </html >
  );
}
