import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Accounts Management System",
    description: "Generated by UIDev",
};

const HrModule = () => {
    return (
        <div>
            <h1>Accounts Management System</h1>
        </div>
    )
}
export default HrModule;