import { auth } from "@/auth";
import ProfileCard from "./profile";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Profile Page",
  description: "Generated by UIDev",
};

const ProfilePage = async () => {
  const session = await auth();
  return (
    <ProfileCard session={session?.user} />
  );
};

export default ProfilePage;
