import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "HR Module",
    description: "Generated by UIDev",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="w-full h-full">
                {children}
            </body>
        </html>
    );
}
