import { auth } from "@/auth";
import DepartmentTable from "./department-table/page";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Department Page",
    description: "Generated by Majedul",
};

const ZonePage = async () => {
    const session = await auth();
    return (
        <DepartmentTable session={session?.user} />
    )
}

export default ZonePage;